---
abstract: 'Configurable URIs for Catalyst'
author:
  - 'Rafael Kitover <rkitover@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.85'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-SmartURI
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.80002
  Class::C3::Componentised: 0
  Task::Weaken: 0
  URI::SmartURI: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.033
